---
- name: Configure Bastion Host
  hosts: role_bastion
  become: yes
  roles:
    - bastion

- name: Configure PostgreSQL Master
  hosts: role_master
  become: yes
  roles:
    - postgres_master

- name: Configure PostgreSQL Replica
  hosts: role_replica
  become: yes
  roles:
    - postgres_replica
