---
# ================== MASTER SETUP ==================
- name: Configure PostgreSQL Master
  hosts: role_master
  remote_user: ubuntu
  become: yes
  roles:
    - postgresql

# ================== REPLICA SETUP ==================
- name: Configure PostgreSQL Replica
  hosts: role_replica
  remote_user: ubuntu
  become: yes
  roles:
    - postgresql
