- include_tasks: install.yml

# Master config
- include_tasks: master.yml
  when: "'role_master' in group_names"

# Replica config 
- include_tasks: replica.yml
  when: "'role_replica' in group_names"
